### ISSUE TITLE
Wrong default value or bug

### ISSUE THREAD

**Issue by hugoeustaquio** [ms-jpq/chadtree#117]
I just installed chadtree, and not configured anything. The docs say the default value of "chadtree_settings.options.show_hidden" is 'false'. But I'm seeing hidden files and directories.

Also, the '.' (dot) key for hidding/showing hidden files is not working, my keyboard is not american.

**Comment by ms-jpq** [comment]
Hi there,

Please set `chadtree_settings.keymap.toggle_hidden`  to whatever key is `.` on your key board:

and for the hidden if you want to hide `.*` things please set `chadtree_settings.ignore.name_glob` to `['.*']`

unlike unix, by default `.*` files are not hidden because so many files used in development start with `.`.

https://github.com/ms-jpq/chadtree/blob/chad/docs/CONFIGURATION.md


https://github.com/ms-jpq/chadtree/blob/chad/docs/KEYBIND.md
