### ISSUE TITLE
Stuck in endless :CHADdeps loop

### ISSUE THREAD

**Issue by AlanWarren** [ms-jpq/chadtree#132]
I've installed chadtree on the latest nvim with vim plug.  I'm running Mac OS Mojave with python3_host_prog configured to use python 3.9.1.  I also have pynvim installed global, as many other plugins require that.   

I've checked the .vars folder is created.  The only thing inside is a runtime directory.  There is no lock file present.  

Instead of installing a virtualenv with pynvim in this manner, is there a configuration option to prefer the global env?  

Looking forward to checking out your plugin. 

Thanks!

**Comment by ms-jpq** [comment]
oh im really sorry I didnt test for `python3_host_prog` in my newest PR, I will push a hotfix

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/commit/c2ea9af4c025ea349857de345ba9a68c4af2e82c

should be fixed

`is there a configuration option to prefer the global env`.

No, global venvs cause too many issues. CHADTree doesn't just rely on `pynvim`, I also wrote `pynvim++` and `std2`, which extract out a lot of the domain agnostic code from CHADTree. I don't want to install that for people globally, since those are basically useless for anybody else and pollute  the namespace.

So previously CHADTree just messed with `PYTHONPATH` or `sys.path` to load packages, but unfortunately that doesn't work if you had installed python under windows using the Microsoft store.

venv is better anyways since now you can install any package you want. Not that it is likely, but the previous method would fail if somebody installed a packaged named `pynvim_pp` or `std2`

**Comment by AlanWarren** [comment]
Thanks for the quick commit, and the explanation.  Makes sense. 

I merged, and now I'm seeing this.  
```
Error detected while processing function CHADon_stderr:
line    1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Press ENTER or type command to continue
Error detected while processing function CHADon_stderr:
line    1:
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
..........  bunch of stuff ............
OSError: [Errno 62] Too many levels of symbolic links: '/Users/wawarren/.config/nvim/plugged/chadtree/.vars/runtime/bin/python3'
```
Which was a bit strange, but I resolved it by setting python3_host_prog to the full path instead of the symlink.   Everything is working now.  appreciate it.

**Comment by ms-jpq** [comment]
yeah cuz of my mistake, it was possible to get to an endless loop because `venv` never expected to create a `venv` on top of itself while running from itself.

Not sure how to solve that exactly, other than me not fucking it up
