### ISSUE TITLE
when I run :CHADopen I get a new empty buffer each time

### ISSUE THREAD

**Issue by jorgebef** [ms-jpq/chadtree#14]
As stated in the title, every time I run the comand to open the CHADTree `:CHADopen` a new empty buffer appears in my current tab.
I'm on Neovim 0.4.3
MacOS Catalina 10.15.6

![Sample image](https://i.imgur.com/MAUh4DU.png)

I don't know if you have encountered this problem before.

Also, when opening CHADtree there is a flicker which leads me to think that it first creates a split and then resizes, which is only a visual thing, but worth noting in case you haven't yet.

And lastly, the buffer with the tree has line numbers, I don't know if this is something that has to be deactivated by the user manually, but I guess it would be good to have it already implemented.

I love the idea and really want to see it progress!!

**Comment by ms-jpq** [comment]
Hi there,

With the help of other contributors I pushed the fixes to the issues you mentioned:

https://github.com/ms-jpq/chadtree/commit/b96d0df2fa98e3ae3c9cebd4b652bb25c8a1d147

https://github.com/ms-jpq/chadtree/commit/f1355603063acc95ddf7cf791386b624c418cad9

Except that line number thing, which I cannot reproduce on a [clean docker image](https://github.com/ms-jpq/chadtree/blob/chad/docker/Dockerfile), I suspect it us due to some conflict with your settings.

You can see I directly do [`setlocal nonumber`](https://github.com/ms-jpq/chadtree/blob/f1355603063acc95ddf7cf791386b624c418cad9/rplugin/python3/chadtree/wm.py#L149) when I create a new tree window.

I suspect something in your configuration is doing the inverse and turning it back on

**Comment by jorgebef** [comment]
The resizing issue is gone!

However there still is one new buffer each time `:CHADopen` is run.

Also just as help to anyone else, the issue with the line numbers seems to come from relative numbers, if I do `:set relativenumber!`and `:set nonumber`then there are no numbers, just nonumber alone won't do the trick.

**Comment by ms-jpq** [comment]
Ah thankyou, I fixed the relative number thing. Didn't know `relativenumber` overwrote `nonumber`.

Im still trying to figure out why it opens a new window for you, since it doesnt do it on my docker image, maybe there is some other vim setting that Im not aware of

**Comment by jorgebef** [comment]
I'm going to try a few checks tomorrow and will edit this comment.

Although, I've been checking about the Scratch type of buffer and I don't know if this applies here, but it might have something to do with the command that is invoked to create this new split, as it may be creating a buffer by using `:new` instead of `:split` as per the info on this github issue for netrw: https://github.com/vim/vim/issues/1016

I guess the option that creates the conflict must be `set hidden`

As I said earlier, I will test tomorrow and get back with more info!!

**Comment by ms-jpq** [comment]
Oh man, thank you so much. I wasn't expecting the help, but it is very welcome!

**Comment by jorgebef** [comment]
Just confirmed `set hidden` is what is interfering here, when wet to `nohidden` the buffer is still created but upon moving to another buffer or closing CHADtree, said buffer dissapears.

I guess providing the `set nobl` option or using `:split` might solve the issue?

If there is anything else I can help with, I'm happy to do so, although my python knowledge is rather limited.

Great support you're giving to the plugin btw, congrats!! =D

**Comment by ms-jpq** [comment]
Ok I patched it with `split`

https://github.com/ms-jpq/chadtree/commit/55ce737198fe9f1d94c05f3bfcd649ce77aace90

It's weird though, because I still cannot reproduce in a solely clean docker image, that makes me think its `hidden` + something else.

This has the side effect of a minor flicker though, since splitting sets it to a different file first, which i still better than whatever is bugged here I guess.

**Comment by jorgebef** [comment]
I can confirm that when I haven't got `:set hidden` it works correctly now!!

I'll close this issue.

**Comment by noisersup** [comment]
I don't know why but it still flickers on my setup
