### ISSUE TITLE
keymap.open_sys (Open file with GUI TOOLS) returning exit status 1

### ISSUE THREAD

**Issue by ghost** [ms-jpq/chadtree#149]
When I try to use the "o" keybind it returns this
```Command '('xdg-open', '--', '/home/yada/.config/polybar/material')' returned non-zero exit status 1.```
I tried using xdg-open on my terminal and it works just not with using CHADTree.

I'm on Ubuntu 20.04 if that's any help. Thanks!

**Comment by offdroid** [comment]
The issue is that the internally executed `xdg-open` command fails.
If I manually call `xdg-open -- /path/to/file`, the equivalent of what gets called internally, I get this error:
```
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
```
Repeating the above command without `--` makes it work as expected.
Why these double dashes are/were added, I don't know. Neither the current version of the [man page](https://portland.freedesktop.org/doc/xdg-open.html) nor any previous one (as far as I can tell) mentions any `--` syntax.
A previous version of chadtree did not include them:
https://github.com/ms-jpq/chadtree/blob/165d92c91e2039829228906036977699f78671e3/chadtree/transitions/open_system.py#L20-L23

Removing the double dashes from the current version
https://github.com/ms-jpq/chadtree/blob/bf5f2bda72265bc7250c16084053924f7f908d53/chadtree/transitions/open_system.py#L22-L24
so that line 23 reads
```python
command = ("xdg-open", path)
```
fixes the issue.

**Comment by ms-jpq** [comment]
oh sorry, i thought `--` helped. ok ill gib it a quickie

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/commit/653945ace36321841852071b59c3a9f67f9dc5e1
