### ISSUE TITLE
Full-Height window

### ISSUE THREAD

**Issue by yngwi** [ms-jpq/chadtree#22]
Hi,

thanks again for your cool plugin. I have a suggestions:

It would be great if the explorer window would open on the leftmost site with full height. Currently (for me at least), the top-leftmost window (if there are more than one vertically split windows) gets split and used for the browser. See the accompanying screenshot. The cursor was in the bottom-rightmost window, the browser opened in the top-left.

![image](https://user-images.githubusercontent.com/963440/89304443-b84c2a00-d66d-11ea-9fc8-b2112ca72482.png)

Daniel

**Comment by ms-jpq** [comment]
good point, this is something that I want to do also, but I think it probably cant be done with re-ordering all the windows? I am not sure if that is a possible to do without closing the windows and reopening them either, will have to invesgiate a bit more.

If it ends up that I will have to close and re-open windows, I'd rather not do it because im 99% sure it can't be done without lots of edge cases.

**Comment by yngwi** [comment]
I'm sorry but I have no idea how it could work, unfortunately. It does in coc-explorer though which is what I've been using so far. Anyways, thank you for your work!

**Comment by ms-jpq** [comment]
I got it.

I was confused, if you want to put a window in any arbitrary position, its alot of work. But if you just want to put it on the side its actually pretty easy.

https://github.com/ms-jpq/chadtree/commit/9bb82b30633a2d88c144da7c97efc531053a69d7

**Comment by yngwi** [comment]
Great, thank you!

**Comment by poetaman** [comment]
@ms-jpq @yngwi How to get CHADopen to open with as a full-height leftmost window?

**Comment by ms-jpq** [comment]
You just use it normally, its the default
