### ISSUE TITLE
Setting directory for :CHADdeps 

### ISSUE THREAD

**Issue by KaranAhlawat** [ms-jpq/chadtree#245]
## Problem
:CHADdeps does not work on NixOS/nix managed systems. Tries to write the dependencies to a read-only location.

## Question
Is there some way to set the dependencies location arbitrarily, instead of just in chadtree/.vars/runtime? I would like to be able to set the dependency install location to somewhere in my home folder ideally.

**Comment by ms-jpq** [comment]
`chadtree_settings.xdg` set it to `true`

it will use `stdpath` from `nvim`

**Comment by imnotpoz** [comment]
hey, I was trying to add chadtree to a flake and it turns out that doesn't fix it entirely, as [TOP_LEVEL](https://github.com/ms-jpq/chadtree/blob/chad/chad_types.py#L6) is set to the parent of that file, which on nixos becomes something like this `/nix/store/wjn7pg5514s98yhdz52cnpaw4didild7-vimplugin-chadtree-master/` which isn't writable and `:CHADdeps` fails

it would work if you checked for the xdg setting and set `TOP_LEVEL` the same as [here](https://github.com/ms-jpq/chadtree/blob/chad/lua/chadtree.lua#L64) but I'm not quite sure how to do that
