### ISSUE TITLE
Colors on Windows

### ISSUE THREAD

**Issue by yngwi** [ms-jpq/chadtree#34]
Hi again,

sorry to open so much issues and thank you for your work! I wonder why chadtree doesn't display colors for instance for folders on my windows install. See my screenshot that has both coc-explorer and chadtree open.

![image](https://user-images.githubusercontent.com/963440/89387588-00695c00-d703-11ea-84d2-3a2ec9448044.png)

**Comment by ms-jpq** [comment]
I suspect you don't have `termguicolors` set am I correct?

If so you will not see the github colours.

I just fixed a bug that hid `LS_COLORS` if they are 8bit. Idk if you have `LS_COLORS` set before, but it should work now.

https://github.com/ms-jpq/chadtree/commit/fd3672a3cdae5327c3d223c12292789fd3595018

**Comment by yngwi** [comment]
Hm actually I do have `set termguicolors` in my vim config. As I said, I'm on windows, maybe that influences things?

**Comment by ms-jpq** [comment]
Do you mind pulling latest commit and see if that changes anything?

I added ability to customize `8bit` -> `24bit` mapping for `LS_COLORS` also, its under the `Colours` section in the readme.

**Comment by yngwi** [comment]
Hi, thank you again for your reply. If I set LS_COLORS as a windows environment parameter the tree is colored:
![image](https://user-images.githubusercontent.com/963440/89681177-b21baf00-d8f4-11ea-9918-e60d22365bb8.png). 

However, the color doesn't follow the color theme in vim while it does so in coc-explorer (for example). Is there a way to make this theme-controlled? I'm sorry if this is a naive question, I have no idea how that kind of thing is supposed to work.

Related to this: I have a function in my vimfiles that switches the theme and/or background color based on time of day or keypress (light/dark) basically calling `colorscheme` and/or `set background` and when I call this function, the colors in the file tree disappear again.

Sorry to bother you, I'm very grateful for your work and support!

**Comment by ms-jpq** [comment]
nono you are not bothering me,

I appreciate the feedback actually, thank you.

So I have an issue in the works that would allow this to follow `colorscheme` on top of `LS_COLORS`

https://github.com/ms-jpq/chadtree/issues/32

The reason I initially designed this to work with `LS_COLORS` instead of vim Highlight groups is because most `LS_COLORS` schemes will include useful information about each file, for example: executables are usually coloured green and such, and sockets will be usually yellow. And symlinks will often be coloured differently depending on if they are dead, or pointing to some actual file.


However, there is enough interest in further customizations that justifies me putting in more work to make it better.

I suspect that COC-explorer have colour theme support because it's more established, and colour themes support it's highlight groups.

See example here: [theme im using right now](https://github.com/sainnhe/edge/blob/master/colors/edge.vim#L312)

It straight up includes COC highlight groups in the theme itself.

So my plan is to basically emulate one of the more popular file explorers, so themes will automatically apply to `CHADTree` as if it is `NerdTree` or something.

I will close this issue, in favour of https://github.com/ms-jpq/chadtree/issues/32

**Comment by yngwi** [comment]
Very cool, thank you!
