### ISSUE TITLE
Flickering on opening 

### ISSUE THREAD

**Issue by anasem** [ms-jpq/chadtree#39]
Hello, 

It seems i'm able again to see the flickering when opening chadtree after plugin update, It seems it opens to default window width and then resized.

Cheers

**Comment by ms-jpq** [comment]
I found the issue, I was trying to prevent flickering but made a typo.

https://github.com/ms-jpq/chadtree/commit/0db1cf901067c17e7a4185f81486e071d7b2213c

I also added a logging system to help catch more issues like this.

https://github.com/ms-jpq/chadtree/blob/chad/rplugin/python3/chadtree/logging.py

Please tell me if you see more flickering issues.

Right now the only circumstance where it should flicker is when you have your window like this

```
|window1|
|-------|
|window2|
```

and you want it to be like this

```
t|window1|
r|       |
e|-------|
e|window2|
 |       |
```

because then I will be forced to do a split and resize afterwards

**Comment by anasem** [comment]
Thank you! it works perfectly now.
