### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by solomonxie** [ms-jpq/chadtree#6]
Hi the plugin looks so interesting but I got problems to load it after many tries.
My environment is:
- MacOS 10.14
- Python 3.7
- Nvim 0.4.3

Here is what I do to install:
- add plugin with vim-plug
- :PlugInstall
- wait for the installment until it's done
- restart nvim
- :CHADopen
- Got error -> `Not an editor command: CHADopen`

Any insights where I did wrong

**Comment by ms-jpq** [comment]
hi there, did you do :UpdateRemotePlugins and restart?

edit maybe you need pynvim, idk if you have it installed

**Comment by jorgebef** [comment]
I had the same issue, turned out I didn't have Python3 set in Nvim.
Run `:checkhealth` command and make sure you have Python3 set correctly and also confirm that you have version 3.8 as what I have read it works for that version correctly but I'm unsure if others run it too.

I hope that fixes it for you!

**Comment by solomonxie** [comment]
For me, it takes these steps to load it up:
1. `:UpdateRemotePlugins`
2. Got error of importing
3. `pip install --user --upgrade pynvim`
4. Restart nvim
5. `:UpdateRemotePlugins`
6. Restart nvim
7. `:CHADopen` command now exists

Although it got an AttributeError after that command, which I believe should be put in another issue page.
Thanks anyway :)

**Comment by ms-jpq** [comment]
ok i will close this issue, sound like u got it
