### ISSUE TITLE
Repo in screen capture.

### ISSUE THREAD

**Issue by Xuyuanp** [ms-jpq/chadtree#86]
Sorry for bothering you. There is no problem for me. I'm interested in the second gif in README. Is it an open-source project in GitHub? Where can I find the source code?

**Comment by ms-jpq** [comment]
this one?

![this one?](https://raw.githubusercontent.com/ms-jpq/chadtree/chad/preview/follow.gif)

that is fzf

**Comment by Xuyuanp** [comment]
![](https://raw.githubusercontent.com/ms-jpq/chadtree/chad/preview/filtering.gif)

This one.

**Comment by ms-jpq** [comment]
[its my personal vimrc](https://github.com/cyproterone/vim)

i have zero guarantees that I won't break anything in there or make breaking changes, or the thing even works on your machine. It is intended to be set up in concert with an ansible playbook that does all the setup.

it's being used with my [personal ansible playbook](https://github.com/cyproterone/ansible-shell), although this is currently broken on MacOS since homebrew has a broken dependency due to `youtube-dl` being taken down for copyright reasons.

you can test it with my [docker image](https://hub.docker.com/repository/docker/msjpq/cli)

run `docker run --rm -it msjpq/cli` and you will get a test run.
